# Generated by Django 5.0 on 2023-12-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apply',
        ),
    ]
